services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11
